name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      run: |
        python --version
        python -m pip install --upgrade pip
    
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
    
    - name: Run tests with coverage
      run: |
        cd backend
        pytest api/tests.py --cov=api --cov-report=term-missing --cov-report=html --cov-report=xml -v
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: backend/htmlcov/
        retention-days: 7